#!/bin/sh

# Copyright 2012 Daniel Rench
# MIT licensed; see the bundled LICENSE file

case "$1" in
    put)
        if [ -z $2 ]; then
            echo "Missing tagname argument!"
            exit 111
        else
            hash=`git hash-object -w --stdin`
            git tag -f $2 $hash > /dev/null
        fi
        ;;
    get)
        if [ -z $2 ]; then
            echo "Missing tagname argument!"
            exit 111
        fi
        git cat-file blob $2
        ;;
    delete)
        if [ -z $2 ]; then
            echo "Missing object name argument!"
            exit 111
        fi
        git tag -d $2
        ;;
    post)
        git hash-object -w --stdin
        ;;
    *)
        echo "usage: git rest [put|get|delete|post] tagname"
        ;;
esac
